["26.1"]
mod.mc_dep_fabric = "26.1.x"
mod.mc_dep_forgelike = "[26.1, 26.2)"
mod.publish_name = "26.1"
mod.publish_versions = "26.1 26.1.1 26.1.2"

#access transformer
mod.at_version = "unversioned"
#class tweaker
mod.ct_version = "unversioned"

["26.1-fabric"]
deps.fabric_version = "0.144.3+26.1"
deps.modmenu_version = "18.0.0-alpha.8"

["26.1-neoforge"]
deps.neoforge_loader = "26.1.0.7-beta"
